---
title: "Microseismic Clustering"
author: "Scott McKean"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
library(msclustering)
library(doParallel)
```

This vignette runs the Gaussian mixture model clustering on a user supplied 
dataset. First we import the data

```{r}
# load data
ms_df <- read_csv('../data/2_processed_msdata.csv') %>%
  filter(mw >= -1.5) %>%
  mutate(well_num = operator_well_num) %>%
  mutate(stage_num = operator_stage_num) %>%
  mutate(well = well_num) %>%
  mutate(stage = stage_num)

survey_df <- read_csv('../data/2_processed_surveys.csv') %>% 
  mutate(well = well_num)
  
comp_df <- read_csv('../data/2_processed_completions.csv') %>%
  mutate(well = well_num) %>%
  mutate(stage = stage_num) %>%
  mutate(r_ap = r_ap * 1.88)

n <- 10000

### MS + PERF ###
registerDoParallel(cores=75)

ms_perf <- out_ms_perf <- foreach (run_n = 1:n, .export = c('ms_df', 'survey_df', 'comp_df'),
         .packages = c('dplyr','mclust', 'msclustering')) %dopar% {
  
  resampled_comp_df <- resample_comp_df(comp_df, survey_df)
  
  resampled_ms_df <- ms_df %>% 
    mutate(x = x + runif(nrow(.), min = -ux, max = ux)) %>%
    mutate(y = y + runif(nrow(.), min = -uy, max = uy)) %>%
    mutate(z = z + runif(nrow(.), min = -uz, max = uz))
  
  ms_class <- classify_ms(ms_df = resampled_ms_df, 
                          comp_df = resampled_comp_df,
                          comp_tcol = 't', ms_tcol = 't')
  
  ms_outlier <- detect_outlier(ms_df = ms_class, 
                               comp_df = resampled_comp_df, 
                               plot = FALSE)
  
  out <- run_gmm_parallel(ms_df = ms_outlier, comp_df = resampled_comp_df, 
                   surv_df = survey_df,  run = run_n, 
                   comp_tcol = 't',  ms_tcol = 't',  plot = FALSE,
                   output_path = '~/2_processed_ms_results/output_ms_perf/')
  
  run_n
}

### MS ONLY ###
registerDoParallel(cores=75)

ms_only <- foreach (run_n = 1:n, .export = c('ms_df', 'survey_df', 'comp_df'),
         .packages = c('dplyr','mclust', 'msclustering')) %dopar% {
  
  run_result <- list()

  resampled_ms_df <- ms_df %>% 
    mutate(x = x + runif(nrow(.), min = -ux, max = ux)) %>%
    mutate(y = y + runif(nrow(.), min = -uy, max = uy)) %>%
    mutate(z = z + runif(nrow(.), min = -uz, max = uz))
  
  ms_class <- classify_ms(ms_df = resampled_ms_df, 
                          comp_df = comp_df,
                          comp_tcol = 't', ms_tcol = 't')
  
  ms_outlier <- detect_outlier(ms_df = ms_class, 
                               comp_df = comp_df, 
                               plot = FALSE)
  
  out <- run_gmm_parallel(ms_df = ms_outlier, comp_df = comp_df, 
                   surv_df = survey_df,  run = run_n, 
                   comp_tcol = 't',  ms_tcol = 't',  plot = FALSE,
                   output_path = '~/2_processed_ms_results/output_ms_only/')
  
  run_n
}
<<<<<<< HEAD
```
=======
  ```
>>>>>>> 9496a4e69b513fb2834cc225aafedf75967f7df9
