---
title: "fractal_plot"
author: "Scott McKean"
date: "7/24/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggsci)
library(fitdistrplus)
```

## Load data for clusters

- Determine category (HF/IS)
- Calculate exponent


```{r}
cluster_df <- read.csv('../output/run_1_clusters.csv') %>% 
  mutate(hf = grepl(pattern = 'HF',x = name)) %>%
  mutate(length = plane_l1, height = plane_l2) %>%
  mutate(length_ecdf = ecdf(plane_l1)(plane_l1)) %>%
  mutate(height_ecdf = ecdf(plane_l2)(plane_l2))

hf_only <- cluster_df %>% filter(hf == 1) %>%
  mutate(length = plane_l1, height = plane_l2) %>%
  mutate(length_ecdf = ecdf(plane_l1)(plane_l1)) %>%
  mutate(height_ecdf = ecdf(plane_l2)(plane_l2))

is_only <- cluster_df %>% filter(hf == 0 ) %>%
  mutate(length = plane_l1, height = plane_l2) %>%
  mutate(length_ecdf = ecdf(plane_l1)(plane_l1)) %>%
  mutate(height_ecdf = ecdf(plane_l2)(plane_l2))
```

## Fit lognormal distributions

```{r}
print('length')
length_lnorm = fitdist(cluster_df %>% filter(hf == 1) %>% pull(length), 
                       distr = 'lnorm')
print('hf')
length_lnorm$estimate
length_pred = rlnorm(10000, length_lnorm$estimate[1], 
                     length_lnorm$estimate[2]) %>% data.frame(hf = .)
length_pred$ecdf_hf = ecdf(length_pred$hf)(length_pred$hf)

length_lnorm = fitdist(cluster_df %>% filter(hf == 0) %>% pull(length), 
                       distr = 'lnorm')
print('is')
length_lnorm$estimate
length_pred$is = rlnorm(10000, length_lnorm$estimate[1], 
                     length_lnorm$estimate[2])
length_pred$ecdf_is = ecdf(length_pred$is)(length_pred$is)


print('height')
height_lnorm = fitdist(cluster_df %>% filter(hf == 1) %>% pull(height), 
                       distr = 'lnorm')
print('hf')
height_lnorm$estimate
height_pred = rlnorm(10000, height_lnorm$estimate[1], 
                     height_lnorm$estimate[2]) %>% data.frame(hf = .)
height_pred$ecdf_hf = ecdf(height_pred$hf)(height_pred$hf)

height_lnorm = fitdist(cluster_df %>% filter(hf == 0) %>% pull(height), 
                       distr = 'lnorm')
print('is')
height_lnorm$estimate
height_pred$is = rlnorm(10000, height_lnorm$estimate[1], 
                     height_lnorm$estimate[2])
height_pred$ecdf_is = ecdf(height_pred$is)(height_pred$is)

```

## Length Graph 

(Two identical panels with Is / HF distributions seperate as stacked graph
is misleading with density plot)



```{r}
ggplot(hf_only) +
  geom_histogram(aes(x = length, ..ncount.., fill = 'Length'), bins = 25, alpha = 0.8) +
  geom_histogram(aes(x = height, ..ncount.., fill = 'Height'), bins = 25, alpha = 0.8) +
  geom_line(aes(x = length, y = (1-length_ecdf))) +
  geom_line(data = length_pred, aes(x = hf, y = (1-ecdf_hf)), colour = 'red') +
  geom_line(aes(x = height, y = (1-height_ecdf))) +
  geom_line(data = height_pred, aes(x = hf, y = (1-ecdf_hf)), colour = 'blue') +
  scale_x_log10(lim = c(1,10000)) +
  scale_fill_manual(name = "",
                    breaks = c('Length', 'Height'),
                    values = c('#4DBBD5B2','#DC0000B2')) +
  theme_minimal() +
  ylab('Probability Density') +
  xlab('Fracture Dimension (m)') +
  theme(legend.position="right") +
  ggsave('hf_fracture_dimensions.png', width = 5, height = 5, dpi = 600)
```

## Height Graph

```{r}
ggplot(is_only) +
  geom_histogram(aes(x = length, ..ncount.., fill = 'Length'), bins = 25, alpha = 0.8) +
  geom_histogram(aes(x = height, ..ncount.., fill = 'Height'), bins = 25, alpha = 0.8) +
  geom_line(aes(x = length, y = (1-length_ecdf))) +
  geom_line(data = length_pred, aes(x = is, y = (1-ecdf_is)), colour = 'red') +
  geom_line(aes(x = height, y = (1-height_ecdf))) +
  geom_line(data = height_pred, aes(x = is, y = (1-ecdf_is)), colour = 'blue') +
  scale_x_log10(lim = c(1,10000)) +
  scale_fill_manual(name = "",
                    breaks = c('Length', 'Height'),
                    values = c('#4DBBD5B2','#DC0000B2')) +
  theme_minimal() +
  ylab('Probability Density') +
  xlab('Fracture Dimension (m)') +
  theme(legend.position="none")  +
  ggsave('is_fracture_dimensions.png', width = 5, height = 5, dpi = 600)

getwd()
```
